services:
  - type: web
    name: fitness-rag-agent
    env: python
    buildCommand: "pip install -r requirements.txt && python ingest.py"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /api/health